import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdtemp, mkdir, writeFile, rm, symlink, chmod } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { auditPluginPackage, detectSecret, formatAuditResult } from "../src/plugin-audit.js";
import { planPluginPack, writePluginPack, PLUGIN_SCHEMA_URL, MCP_SCHEMA_URL } from "../src/plugin-pack.js";

let root: string;

beforeEach(async () => {
  root = await mkdtemp(path.join(tmpdir(), "umt-audit-"));
});

afterEach(async () => {
  await rm(root, { recursive: true, force: true });
});

async function writePkg(files: Record<string, string>): Promise<string> {
  const dir = path.join(root, `pkg-${Math.random().toString(36).slice(2)}`);
  for (const [rel, content] of Object.entries(files)) {
    const abs = path.join(dir, rel);
    await mkdir(path.dirname(abs), { recursive: true });
    await writeFile(abs, content, "utf8");
  }
  return dir;
}

function goodPluginJson(overrides: Record<string, unknown> = {}): string {
  return JSON.stringify(
    {
      $schema: PLUGIN_SCHEMA_URL,
      name: "my-pack",
      version: "1.0.0",
      description: "test pack",
      license: "MIT",
      ...overrides,
    },
    null,
    2,
  );
}

function goodMcpJson(overrides: Record<string, unknown> = {}): string {
  return JSON.stringify(
    {
      $schema: MCP_SCHEMA_URL,
      mcpServers: {
        "umt-github": {
          type: "stdio",
          command: "npx",
          args: ["-y", "@universal-mcp-toolkit/server-github", "--transport", "stdio"],
          env: { GITHUB_TOKEN: "${GITHUB_TOKEN}" },
        },
      },
      ...overrides,
    },
    null,
    2,
  );
}

describe("detectSecret", () => {
  it("allows ${VAR} placeholders", () => {
    expect(detectSecret("${GITHUB_TOKEN}")).toBeNull();
    expect(detectSecret("  ${SOME_KEY}  ")).toBeNull();
  });

  it("detects known token shapes", () => {
    expect(detectSecret("sk-abcdefghijklmnopqrstuvwx")).toBe("openai-key");
    expect(detectSecret("ghp_" + "a".repeat(36))).toBe("github-token");
    expect(detectSecret("xoxb-123456789012-abcdefghij")).toBe("slack-token");
    expect(detectSecret("AKIA" + "A".repeat(16))).toBe("aws-access-key");
    expect(detectSecret("-----BEGIN RSA PRIVATE KEY-----")).toBe("private-key");
  });

  it("detects credential assignments", () => {
    expect(detectSecret('api_key: "supersecretvalue123"')).toBe("credential-assignment");
    expect(detectSecret("password=hunter2hunter2")).toBe("credential-assignment");
  });

  it("does not flag ordinary prose", () => {
    expect(detectSecret("Requires environment variables: GITHUB_TOKEN.")).toBeNull();
    expect(detectSecret("use the github token from your settings")).toBeNull();
    expect(detectSecret("")).toBeNull();
  });
});

describe("auditPluginPackage — happy path", () => {
  it("passes a well-formed package with no findings", async () => {
    const dir = await writePkg({
      "plugin.json": goodPluginJson(),
      "mcp.json": goodMcpJson(),
      "skills/umt-github/SKILL.md": "---\nname: umt-github\ndescription: d\n---\n\n# body\n",
    });
    const result = await auditPluginPackage(dir);
    expect(result.ok).toBe(true);
    expect(result.errors).toEqual([]);
    expect(result.warnings).toEqual([]);
    expect(formatAuditResult(result)).toContain("passed");
  });

  it("passes a package generated by `umt plugin pack`", async () => {
    const outDir = path.join(root, "packed");
    const plan = planPluginPack({ name: "my-pack", serverIds: ["github", "notion"], outDir }, "1.0.0");
    await writePluginPack(plan);
    const result = await auditPluginPackage(outDir);
    expect(result.errors).toEqual([]);
    expect(result.ok).toBe(true);
  });

  it("tolerates reverse-domain client namespace dirs", async () => {
    const dir = await writePkg({
      "plugin.json": goodPluginJson(),
      "com.example.client/notes.txt": "client-specific",
    });
    const result = await auditPluginPackage(dir);
    expect(result.errors).toEqual([]);
  });
});

describe("auditPluginPackage — manifest schema", () => {
  it("errors when plugin.json is missing", async () => {
    const dir = await writePkg({ "mcp.json": goodMcpJson() });
    const result = await auditPluginPackage(dir);
    expect(result.ok).toBe(false);
    expect(result.errors.some((f) => f.code === "schema/plugin-missing")).toBe(true);
  });

  it("errors on unparseable plugin.json", async () => {
    const dir = await writePkg({ "plugin.json": "{ not json" });
    const result = await auditPluginPackage(dir);
    expect(result.errors.some((f) => f.code === "schema/plugin-unparseable")).toBe(true);
  });

  it("errors on wrong $schema and invalid name", async () => {
    const dir = await writePkg({
      "plugin.json": goodPluginJson({ $schema: "https://example.com/other.json", name: "BAD NAME" }),
    });
    const result = await auditPluginPackage(dir);
    expect(result.errors.some((f) => f.code === "schema/plugin-schema-mismatch")).toBe(true);
    expect(result.errors.some((f) => f.code === "schema/plugin-name-invalid")).toBe(true);
  });

  it("warns (not errors) on unknown top-level fields", async () => {
    const dir = await writePkg({ "plugin.json": goodPluginJson({ frobnicate: true }) });
    const result = await auditPluginPackage(dir);
    expect(result.ok).toBe(true);
    expect(result.warnings.some((f) => f.code === "schema/plugin-unknown-field")).toBe(true);
  });
});

describe("auditPluginPackage — mcp.json", () => {
  it("errors when a stdio command is multi-token or absolute", async () => {
    const dir = await writePkg({
      "plugin.json": goodPluginJson(),
      "mcp.json": goodMcpJson({
        mcpServers: {
          bad1: { type: "stdio", command: "npx -y evil" },
          bad2: { type: "stdio", command: "/usr/bin/evil" },
        },
      }),
    });
    const result = await auditPluginPackage(dir);
    expect(result.errors.some((f) => f.code === "schema/mcp-stdio-command-multi-token")).toBe(true);
    expect(result.errors.some((f) => f.code === "path/mcp-stdio-command-absolute")).toBe(true);
  });

  it("errors when cwd escapes the package root", async () => {
    const dir = await writePkg({
      "plugin.json": goodPluginJson(),
      "mcp.json": goodMcpJson({ mcpServers: { bad: { type: "stdio", command: "npx", cwd: "../../etc" } } }),
    });
    const result = await auditPluginPackage(dir);
    expect(result.errors.some((f) => f.code === "path/mcp-stdio-cwd-escape")).toBe(true);
  });

  it("accepts ${PLUGIN_ROOT}-anchored cwd", async () => {
    const dir = await writePkg({
      "plugin.json": goodPluginJson(),
      "mcp.json": goodMcpJson({
        mcpServers: { ok: { type: "stdio", command: "npx", cwd: "${PLUGIN_ROOT}/bin" } },
      }),
    });
    const result = await auditPluginPackage(dir);
    expect(result.errors).toEqual([]);
  });

  it("rejects insecure remote http urls but allows https and loopback", async () => {
    const dir = await writePkg({
      "plugin.json": goodPluginJson(),
      "mcp.json": goodMcpJson({
        mcpServers: {
          insecure: { type: "streamable-http", url: "http://evil.example.com/mcp" },
          secure: { type: "streamable-http", url: "https://example.com/mcp" },
          loop: { type: "streamable-http", url: "http://localhost:3000/mcp" },
        },
      }),
    });
    const result = await auditPluginPackage(dir);
    const insecure = result.errors.filter((f) => f.code === "schema/mcp-http-url-insecure");
    expect(insecure).toHaveLength(1);
    expect(insecure[0]!.message).toContain("evil.example.com");
  });

  it("warns on deprecated sse transport", async () => {
    const dir = await writePkg({
      "plugin.json": goodPluginJson(),
      "mcp.json": goodMcpJson({ mcpServers: { old: { type: "sse", url: "https://example.com/sse" } } }),
    });
    const result = await auditPluginPackage(dir);
    expect(result.ok).toBe(true);
    expect(result.warnings.some((f) => f.code === "schema/mcp-server-type-deprecated")).toBe(true);
  });

  it("rejects unknown server types", async () => {
    const dir = await writePkg({
      "plugin.json": goodPluginJson(),
      "mcp.json": goodMcpJson({ mcpServers: { bad: { type: "websocket", url: "https://x" } } }),
    });
    const result = await auditPluginPackage(dir);
    expect(result.errors.some((f) => f.code === "schema/mcp-server-type-invalid")).toBe(true);
  });
});

describe("auditPluginPackage — secrets", () => {
  it("errors on credential-shaped env values", async () => {
    const dir = await writePkg({
      "plugin.json": goodPluginJson(),
      "mcp.json": goodMcpJson({
        mcpServers: {
          leaked: {
            type: "stdio",
            command: "npx",
            args: ["-y", "pkg"],
            env: { GITHUB_TOKEN: "ghp_" + "a".repeat(36) },
          },
        },
      }),
    });
    const result = await auditPluginPackage(dir);
    expect(result.ok).toBe(false);
    expect(result.errors.some((f) => f.code === "secret/mcp-env")).toBe(true);
    expect(formatAuditResult(result)).toContain("FAILED");
  });

  it("errors on credential-shaped header values", async () => {
    const dir = await writePkg({
      "plugin.json": goodPluginJson(),
      "mcp.json": goodMcpJson({
        mcpServers: {
          leaked: {
            type: "streamable-http",
            url: "https://example.com/mcp",
            headers: { Authorization: "Bearer abcdefghijklmnopqrstuvwx" },
          },
        },
      }),
    });
    const result = await auditPluginPackage(dir);
    expect(result.errors.some((f) => f.code === "secret/mcp-headers")).toBe(true);
  });

  it("errors on secrets smuggled into a skill body", async () => {
    const dir = await writePkg({
      "plugin.json": goodPluginJson(),
      "skills/evil/SKILL.md": "---\nname: evil\ndescription: d\n---\n\ntoken: sk-abcdefghijklmnopqrstuvwx\n",
    });
    const result = await auditPluginPackage(dir);
    expect(result.errors.some((f) => f.code === "secret/skill-body")).toBe(true);
  });
});

describe("auditPluginPackage — component isolation", () => {
  it("errors when a skill declares mcpServers", async () => {
    const dir = await writePkg({
      "plugin.json": goodPluginJson(),
      "skills/evil/SKILL.md": '---\nname: evil\ndescription: d\n---\n\n```json\n{ "mcpServers": {} }\n```\n',
    });
    const result = await auditPluginPackage(dir);
    expect(result.errors.some((f) => f.code === "isolation/skill-smuggled-servers")).toBe(true);
  });

  it("errors when a skill dir contains mcp.json", async () => {
    const dir = await writePkg({
      "plugin.json": goodPluginJson(),
      "skills/evil/SKILL.md": "---\nname: evil\ndescription: d\n---\n",
      "skills/evil/mcp.json": "{}",
    });
    const result = await auditPluginPackage(dir);
    expect(result.errors.some((f) => f.code === "isolation/skill-smuggled-manifest")).toBe(true);
  });

  it("warns when a skill dir lacks SKILL.md (failure isolation, not fatal)", async () => {
    const dir = await writePkg({
      "plugin.json": goodPluginJson(),
      "skills/empty/notes.txt": "no manifest here",
    });
    const result = await auditPluginPackage(dir);
    expect(result.ok).toBe(true);
    expect(result.warnings.some((f) => f.code === "schema/skill-missing-manifest")).toBe(true);
  });

  it("warns on executable files", async () => {
    const dir = await writePkg({
      "plugin.json": goodPluginJson(),
      "skills/tool/SKILL.md": "---\nname: tool\ndescription: d\n---\n",
      "skills/tool/run.sh": "#!/bin/sh\necho hi\n",
    });
    await chmod(path.join(dir, "skills/tool/run.sh"), 0o755);
    const result = await auditPluginPackage(dir);
    expect(result.ok).toBe(true);
    expect(result.warnings.some((f) => f.code === "isolation/unexpected-executable")).toBe(true);
  });

  it("errors on symlinks escaping the package root", async () => {
    const dir = await writePkg({ "plugin.json": goodPluginJson() });
    await symlink("/etc/passwd", path.join(dir, "evil-link"));
    const result = await auditPluginPackage(dir);
    expect(result.errors.some((f) => f.code === "path/symlink-escape")).toBe(true);
  });

  it("warns on unrecognized root component dirs", async () => {
    const dir = await writePkg({
      "plugin.json": goodPluginJson(),
      "random-stuff/x.txt": "huh",
    });
    const result = await auditPluginPackage(dir);
    expect(result.ok).toBe(true);
    expect(result.warnings.some((f) => f.code === "schema/unknown-component-dir")).toBe(true);
  });
});

describe("auditPluginPackage — robustness", () => {
  it("reports a missing directory as an error, never throws", async () => {
    const result = await auditPluginPackage(path.join(root, "does-not-exist"));
    expect(result.ok).toBe(false);
    expect(result.errors.some((f) => f.code === "path/root-missing")).toBe(true);
  });
});
