export type ConfigTarget = "claude-desktop" | "cursor" | "json";

export type InvocationMode = "npx" | "workspace";

export interface ServerRegistryEntry {
  id: string;
  title: string;
  category: string;
  description: string;
  packageName: string;
  npxArgs?: readonly string[];
  envVarNames: readonly string[];
  transports: readonly ("stdio" | "sse" | "streamable-http")[];
  /**
   * The list of tool names exposed by this server.
   * Populated from the server's well-known/mcp-server.json `tools` array.
   * Used by `umt list` to show tool counts and by `umt search` to match
   * tool names in addition to server names and descriptions.
   */
  toolNames: readonly string[];
  experimental?: boolean;
}

export const SERVER_REGISTRY: readonly ServerRegistryEntry[] = [
  {
    id: "github",
    title: "GitHub",
    category: "Collaboration",
    description: "Repository search, pull requests, workflows, and issue triage.",
    packageName: "@universal-mcp-toolkit/server-github",
    envVarNames: ["GITHUB_TOKEN"],
    transports: ["stdio", "sse"],
    toolNames: ["get_pull_request", "list_workflow_runs", "search_repositories"],
  },
  {
    id: "notion",
    title: "Notion",
    category: "Collaboration",
    description: "Search pages and databases, read docs, and publish structured notes.",
    packageName: "@universal-mcp-toolkit/server-notion",
    envVarNames: ["NOTION_TOKEN"],
    transports: ["stdio", "sse"],
    toolNames: ["search-pages", "get-page", "create-page"],
  },
  {
    id: "slack",
    title: "Slack",
    category: "Collaboration",
    description: "Look up channels, fetch threads, and post workspace updates.",
    packageName: "@universal-mcp-toolkit/server-slack",
    envVarNames: ["SLACK_BOT_TOKEN"],
    transports: ["stdio", "sse"],
    toolNames: ["list_channels", "fetch_channel_history", "post_message"],
  },
  {
    id: "linear",
    title: "Linear",
    category: "Collaboration",
    description: "Search issues, inspect workflow state, and create new work items.",
    packageName: "@universal-mcp-toolkit/server-linear",
    envVarNames: ["LINEAR_API_KEY"],
    transports: ["stdio", "sse"],
    toolNames: ["search_issues", "get_issue", "create_issue"],
  },
  {
    id: "jira",
    title: "Jira",
    category: "Collaboration",
    description: "Search issues, inspect tickets, and drive incident triage.",
    packageName: "@universal-mcp-toolkit/server-jira",
    envVarNames: ["JIRA_BASE_URL", "JIRA_EMAIL", "JIRA_API_TOKEN"],
    transports: ["stdio", "sse"],
    toolNames: ["get_issue", "search_issues", "transition_issue"],
  },
  {
    id: "google-calendar",
    title: "Google Calendar",
    category: "Productivity",
    description: "List calendars, inspect events, and schedule meetings.",
    packageName: "@universal-mcp-toolkit/server-google-calendar",
    envVarNames: ["GOOGLE_CALENDAR_ACCESS_TOKEN"],
    transports: ["stdio", "sse"],
    toolNames: ["list-calendars", "list-events", "create-event"],
  },
  {
    id: "google-drive",
    title: "Google Drive",
    category: "Productivity",
    description: "Search Drive, inspect document metadata, and export files.",
    packageName: "@universal-mcp-toolkit/server-google-drive",
    envVarNames: ["GOOGLE_DRIVE_ACCESS_TOKEN"],
    transports: ["stdio", "sse"],
    toolNames: ["search-files", "get-file-metadata", "export-file"],
  },
  {
    id: "spotify",
    title: "Spotify",
    category: "Media & Commerce",
    description: "Search tracks, inspect playback, and curate playlists.",
    packageName: "@universal-mcp-toolkit/server-spotify",
    envVarNames: ["SPOTIFY_ACCESS_TOKEN"],
    transports: ["stdio", "sse"],
    toolNames: ["currently-playing", "search-tracks", "list-playlists"],
  },
  {
    id: "stripe",
    title: "Stripe",
    category: "Media & Commerce",
    description: "Inspect billing state, customers, invoices, and subscriptions.",
    packageName: "@universal-mcp-toolkit/server-stripe",
    envVarNames: ["STRIPE_SECRET_KEY"],
    transports: ["stdio", "sse"],
    toolNames: ["list-customers", "get-invoice", "list-subscriptions"],
  },
  {
    id: "postgresql",
    title: "PostgreSQL",
    category: "Data",
    description: "Inspect schemas and run guarded SQL queries.",
    packageName: "@universal-mcp-toolkit/server-postgresql",
    envVarNames: ["POSTGRESQL_URL"],
    transports: ["stdio", "sse"],
    toolNames: ["list-tables", "describe-table", "run-query"],
  },
  {
    id: "mongodb",
    title: "MongoDB",
    category: "Data",
    description: "Explore collections and run filtered document queries.",
    packageName: "@universal-mcp-toolkit/server-mongodb",
    envVarNames: ["MONGODB_URI"],
    transports: ["stdio", "sse"],
    toolNames: ["list-collections", "find-documents", "aggregate-documents"],
  },
  {
    id: "redis",
    title: "Redis",
    category: "Data",
    description: "Inspect keys, TTLs, and runtime cache diagnostics.",
    packageName: "@universal-mcp-toolkit/server-redis",
    envVarNames: ["REDIS_URL"],
    transports: ["stdio", "sse"],
    toolNames: ["get-key", "set-key", "inspect-server-info"],
  },
  {
    id: "supabase",
    title: "Supabase",
    category: "Data",
    description: "Query tables, storage, and operational project metadata.",
    packageName: "@universal-mcp-toolkit/server-supabase",
    envVarNames: ["SUPABASE_URL", "SUPABASE_KEY"],
    transports: ["stdio", "sse"],
    toolNames: ["list-tables", "query-table", "list-storage-buckets"],
  },
  {
    id: "vercel",
    title: "Vercel",
    category: "Platform",
    description: "Track projects, deployments, and environment settings.",
    packageName: "@universal-mcp-toolkit/server-vercel",
    envVarNames: ["VERCEL_TOKEN"],
    transports: ["stdio", "sse"],
    toolNames: ["list_projects", "list_deployments", "get_deployment"],
  },
  {
    id: "cloudflare-workers",
    title: "Cloudflare Workers",
    category: "Platform",
    description: "Inspect workers, routes, and edge rollout state.",
    packageName: "@universal-mcp-toolkit/server-cloudflare-workers",
    envVarNames: ["CLOUDFLARE_API_TOKEN", "CLOUDFLARE_ACCOUNT_ID"],
    transports: ["stdio", "sse"],
    toolNames: ["list_workers", "get_worker", "list_routes"],
  },
  {
    id: "docker",
    title: "Docker",
    category: "Platform",
    description: "Inspect containers, images, and daemon state.",
    packageName: "@universal-mcp-toolkit/server-docker",
    envVarNames: [],
    transports: ["stdio", "sse"],
    toolNames: ["list_containers", "inspect_container", "list_images"],
  },
  {
    id: "npm-registry",
    title: "NPM Registry",
    category: "Platform",
    description: "Search packages, inspect versions, and review release metadata.",
    packageName: "@universal-mcp-toolkit/server-npm-registry",
    envVarNames: [],
    transports: ["stdio", "sse"],
    toolNames: ["search_packages", "get_package_metadata", "list_package_versions"],
  },
  {
    id: "hackernews",
    title: "Hacker News",
    category: "Research",
    description: "Search trends, fetch top stories, and inspect discussion threads.",
    packageName: "@universal-mcp-toolkit/server-hackernews",
    envVarNames: [],
    transports: ["stdio", "sse"],
    toolNames: ["get_top_stories", "search_stories", "get_item_thread"],
  },
  {
    id: "arxiv",
    title: "arXiv",
    category: "Research",
    description: "Search papers and build compact literature digests.",
    packageName: "@universal-mcp-toolkit/server-arxiv",
    envVarNames: [],
    transports: ["stdio", "sse"],
    toolNames: ["search_papers", "get_paper", "list_recent_papers"],
    experimental: true,
  },
  {
    id: "filesystem",
    title: "FileSystem",
    category: "Local",
    description: "Read and write files safely inside explicitly allowed roots.",
    packageName: "@universal-mcp-toolkit/server-filesystem",
    envVarNames: ["FILESYSTEM_ROOTS"],
    transports: ["stdio", "sse"],
    toolNames: ["list_files", "read_file", "write_file"],
  },
  {
    id: "discord",
    title: "Discord",
    category: "Collaboration",
    description: "Guild discovery, channel lookup, message history, and messaging.",
    packageName: "@universal-mcp-toolkit/server-discord",
    envVarNames: ["DISCORD_BOT_TOKEN"],
    transports: ["stdio", "sse"],
    toolNames: ["discord_list_guilds", "discord_list_channels", "discord_get_messages", "discord_send_message", "discord_get_guild_members"],
  },
  {
    id: "airtable",
    title: "Airtable",
    category: "Data",
    description: "Table listing, record CRUD, and filtering for Airtable bases.",
    packageName: "@universal-mcp-toolkit/server-airtable",
    envVarNames: ["AIRTABLE_API_KEY", "AIRTABLE_BASE_ID"],
    transports: ["stdio", "sse"],
    toolNames: ["airtable_list_tables", "airtable_get_records", "airtable_create_record", "airtable_update_record", "airtable_delete_record"],
  },
  {
    id: "trello",
    title: "Trello",
    category: "Collaboration",
    description: "Board and list discovery, card CRUD, and archiving.",
    packageName: "@universal-mcp-toolkit/server-trello",
    envVarNames: ["TRELLO_API_KEY", "TRELLO_TOKEN"],
    transports: ["stdio", "sse"],
    toolNames: ["trello_list_boards", "trello_list_lists", "trello_list_cards", "trello_create_card", "trello_update_card", "trello_archive_card"],
  },
  {
    id: "memos",
    title: "MemOS",
    category: "Memory",
    description: "Local-first persistent memory over MCP, backed by a MemOS SQLite database.",
    packageName: "@mem-os/sdk",
    npxArgs: ["-y", "@mem-os/sdk", "mcp"],
    envVarNames: [],
    transports: ["stdio"],
    toolNames: [],
  },
  {
    id: "notion-mcp",
    title: "Notion (MCP)",
    category: "Collaboration",
    description: "Full Notion workspace integration with search, CRUD on pages and databases.",
    packageName: "@contextcore/mcp-notion",
    envVarNames: ["NOTION_API_KEY"],
    transports: ["stdio", "sse"],
    toolNames: [],
  },
  {
    id: "playwright-mcp",
    title: "Playwright (MCP)",
    category: "Automation",
    description: "Browser automation and web scraping with Playwright.",
    packageName: "@contextcore/mcp-playwright",
    envVarNames: [],
    transports: ["stdio", "sse"],
    toolNames: [],
  },
  {
    id: "slack-mcp",
    title: "Slack (MCP)",
    category: "Collaboration",
    description: "Full Slack workspace integration with channels, messages, users, and files.",
    packageName: "@contextcore/mcp-slack",
    envVarNames: ["SLACK_BOT_TOKEN"],
    transports: ["stdio", "sse"],
    toolNames: [],
  },
  {
    id: "openai-mcp",
    title: "OpenAI (MCP)",
    category: "AI",
    description: "OpenAI/Codex API integration with chat, completion, embedding, and more.",
    packageName: "@contextcore/mcp-openai",
    envVarNames: ["OPENAI_API_KEY"],
    transports: ["stdio", "sse"],
    toolNames: [],
  }
];
export function getRegistryEntry(id: string): ServerRegistryEntry {
  const entry = SERVER_REGISTRY.find((candidate) => candidate.id === id);
  if (!entry) {
    throw new Error(`Unknown server '${id}'.`);
  }

  return entry;
}
